language: php
php:
  - 7.3

before_script:
  - composer self-update
  - composer install
  - chmod -R 777 storage
  - php artisan key:generate

script: 
  - ./vendor/bin/phpunit

notifications:
  emails:
    - narishige7@gmail.com